name: taluxi
description: Taluxi project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  user_manager:
    path: ../packages/user_manager
  cupertino_icons: ^1.0.0
  firebase_core: ^0.5.3
  firebase_messaging: ^7.0.3
  flutter_svg: 0.19.1
  google_fonts: ^1.1.1
  google_maps_flutter: ^1.0.6
  lottie: ^0.7.0+1
  provider: ^4.3.2+3
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.3
  test: ^1.15.7

flutter:

  assets:
    - assets/images/
    - assets/images/animations/
    # - assets/map_styles/dark_.json
    # - assets/map_styles/light.json

  uses-material-design: true
